apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.deployment.name }}
  labels:
    app: {{ .Values.global.deployment.name }}
spec:
  selector:
    app: {{ .Values.global.deployment.name }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.deployment.name }}
  labels:
    app: {{ .Values.global.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.global.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.deployment.name }}
    spec:
      containers:
        - image: {{ .Values.global.deployment.image }}
          name: metrics-provider
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
          imagePullPolicy: Always