apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.statefulset.name }}
  labels:
    app: {{ .Values.global.statefulset.name }}
spec:
  ports:
    - port: 8081
      name: web
  clusterIP: None
  selector:
    app: {{ .Values.global.statefulset.name }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.global.statefulset.name}}
spec:
  serviceName: {{ .Values.global.statefulset.name }}
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.global.statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.statefulset.name }}
    spec:
      containers:
        - name: {{ .Values.global.statefulset.name }}
          image: harbor.archeros.cn/dev/hpa-statefulset:v1
          ports:
            - containerPort: 8081
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 1Gi
          imagePullPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        storageClassName: hpa-demo
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi